markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Asif Kalam
url: http://asifskalam.com
description: Asif S Kalam's homepage.
twitter: asifskalam
github: asifkalam
gravatar_url: https://en.gravatar.com/userimage/466158/a4488174b34664bb188e8a72bfbf3533
